// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: got.proto

package gotgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreType int32

const (
	StoreType_UNKNOWN StoreType = 0
	StoreType_RAW     StoreType = 1
	StoreType_FS      StoreType = 2
	StoreType_VC      StoreType = 3
)

// Enum value maps for StoreType.
var (
	StoreType_name = map[int32]string{
		0: "UNKNOWN",
		1: "RAW",
		2: "FS",
		3: "VC",
	}
	StoreType_value = map[string]int32{
		"UNKNOWN": 0,
		"RAW":     1,
		"FS":      2,
		"VC":      3,
	}
)

func (x StoreType) Enum() *StoreType {
	p := new(StoreType)
	*p = x
	return p
}

func (x StoreType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StoreType) Descriptor() protoreflect.EnumDescriptor {
	return file_got_proto_enumTypes[0].Descriptor()
}

func (StoreType) Type() protoreflect.EnumType {
	return &file_got_proto_enumTypes[0]
}

func (x StoreType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StoreType.Descriptor instead.
func (StoreType) EnumDescriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{0}
}

type Mode int32

const (
	Mode_FROZEN Mode = 0
	Mode_EXPAND Mode = 1
	Mode_SHRINK Mode = 2
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "FROZEN",
		1: "EXPAND",
		2: "SHRINK",
	}
	Mode_value = map[string]int32{
		"FROZEN": 0,
		"EXPAND": 1,
		"SHRINK": 2,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_got_proto_enumTypes[1].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_got_proto_enumTypes[1]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{1}
}

type Annotation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Annotation) Reset() {
	*x = Annotation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Annotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Annotation) ProtoMessage() {}

func (x *Annotation) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Annotation.ProtoReflect.Descriptor instead.
func (*Annotation) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{0}
}

func (x *Annotation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Annotation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type BranchInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Salt        []byte        `protobuf:"bytes,1,opt,name=salt,proto3" json:"salt,omitempty"`
	CreatedAt   []byte        `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Annotations []*Annotation `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty"`
}

func (x *BranchInfo) Reset() {
	*x = BranchInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BranchInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchInfo) ProtoMessage() {}

func (x *BranchInfo) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchInfo.ProtoReflect.Descriptor instead.
func (*BranchInfo) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{1}
}

func (x *BranchInfo) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *BranchInfo) GetCreatedAt() []byte {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BranchInfo) GetAnnotations() []*Annotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type CreateBranchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Salt []byte `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
}

func (x *CreateBranchReq) Reset() {
	*x = CreateBranchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBranchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBranchReq) ProtoMessage() {}

func (x *CreateBranchReq) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBranchReq.ProtoReflect.Descriptor instead.
func (*CreateBranchReq) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBranchReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateBranchReq) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

type GetBranchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetBranchReq) Reset() {
	*x = GetBranchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBranchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBranchReq) ProtoMessage() {}

func (x *GetBranchReq) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBranchReq.ProtoReflect.Descriptor instead.
func (*GetBranchReq) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{3}
}

func (x *GetBranchReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SetBranchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key         string        `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Salt        []byte        `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	Mode        Mode          `protobuf:"varint,3,opt,name=mode,proto3,enum=Mode" json:"mode,omitempty"`
	Annotations []*Annotation `protobuf:"bytes,4,rep,name=annotations,proto3" json:"annotations,omitempty"`
}

func (x *SetBranchReq) Reset() {
	*x = SetBranchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetBranchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBranchReq) ProtoMessage() {}

func (x *SetBranchReq) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBranchReq.ProtoReflect.Descriptor instead.
func (*SetBranchReq) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{4}
}

func (x *SetBranchReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetBranchReq) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *SetBranchReq) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_FROZEN
}

func (x *SetBranchReq) GetAnnotations() []*Annotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type ListBranchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Begin string `protobuf:"bytes,1,opt,name=begin,proto3" json:"begin,omitempty"`
	End   string `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *ListBranchReq) Reset() {
	*x = ListBranchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBranchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBranchReq) ProtoMessage() {}

func (x *ListBranchReq) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBranchReq.ProtoReflect.Descriptor instead.
func (*ListBranchReq) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{5}
}

func (x *ListBranchReq) GetBegin() string {
	if x != nil {
		return x.Begin
	}
	return ""
}

func (x *ListBranchReq) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

type ListBranchRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *ListBranchRes) Reset() {
	*x = ListBranchRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBranchRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBranchRes) ProtoMessage() {}

func (x *ListBranchRes) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBranchRes.ProtoReflect.Descriptor instead.
func (*ListBranchRes) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{6}
}

func (x *ListBranchRes) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type DeleteBranchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *DeleteBranchReq) Reset() {
	*x = DeleteBranchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBranchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBranchReq) ProtoMessage() {}

func (x *DeleteBranchReq) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBranchReq.ProtoReflect.Descriptor instead.
func (*DeleteBranchReq) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBranchReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteBranchRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteBranchRes) Reset() {
	*x = DeleteBranchRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBranchRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBranchRes) ProtoMessage() {}

func (x *DeleteBranchRes) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBranchRes.ProtoReflect.Descriptor instead.
func (*DeleteBranchRes) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{8}
}

type PostBlobReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	StoreType StoreType `protobuf:"varint,2,opt,name=store_type,json=storeType,proto3,enum=StoreType" json:"store_type,omitempty"`
	Data      []byte    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PostBlobReq) Reset() {
	*x = PostBlobReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostBlobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBlobReq) ProtoMessage() {}

func (x *PostBlobReq) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBlobReq.ProtoReflect.Descriptor instead.
func (*PostBlobReq) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{9}
}

func (x *PostBlobReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PostBlobReq) GetStoreType() StoreType {
	if x != nil {
		return x.StoreType
	}
	return StoreType_UNKNOWN
}

func (x *PostBlobReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PostBlobRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PostBlobRes) Reset() {
	*x = PostBlobRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostBlobRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBlobRes) ProtoMessage() {}

func (x *PostBlobRes) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBlobRes.ProtoReflect.Descriptor instead.
func (*PostBlobRes) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{10}
}

func (x *PostBlobRes) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetBlobReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	StoreType StoreType `protobuf:"varint,2,opt,name=store_type,json=storeType,proto3,enum=StoreType" json:"store_type,omitempty"`
	Id        []byte    `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBlobReq) Reset() {
	*x = GetBlobReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobReq) ProtoMessage() {}

func (x *GetBlobReq) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobReq.ProtoReflect.Descriptor instead.
func (*GetBlobReq) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{11}
}

func (x *GetBlobReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetBlobReq) GetStoreType() StoreType {
	if x != nil {
		return x.StoreType
	}
	return StoreType_UNKNOWN
}

func (x *GetBlobReq) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetBlobRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetBlobRes) Reset() {
	*x = GetBlobRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlobRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobRes) ProtoMessage() {}

func (x *GetBlobRes) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobRes.ProtoReflect.Descriptor instead.
func (*GetBlobRes) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{12}
}

func (x *GetBlobRes) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddBlobReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	StoreType StoreType `protobuf:"varint,2,opt,name=store_type,json=storeType,proto3,enum=StoreType" json:"store_type,omitempty"`
	Id        []byte    `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AddBlobReq) Reset() {
	*x = AddBlobReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBlobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBlobReq) ProtoMessage() {}

func (x *AddBlobReq) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBlobReq.ProtoReflect.Descriptor instead.
func (*AddBlobReq) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{13}
}

func (x *AddBlobReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AddBlobReq) GetStoreType() StoreType {
	if x != nil {
		return x.StoreType
	}
	return StoreType_UNKNOWN
}

func (x *AddBlobReq) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type AddBlobRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddBlobRes) Reset() {
	*x = AddBlobRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBlobRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBlobRes) ProtoMessage() {}

func (x *AddBlobRes) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBlobRes.ProtoReflect.Descriptor instead.
func (*AddBlobRes) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{14}
}

type ListBlobReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	StoreType StoreType `protobuf:"varint,2,opt,name=store_type,json=storeType,proto3,enum=StoreType" json:"store_type,omitempty"`
	Begin     []byte    `protobuf:"bytes,3,opt,name=begin,proto3" json:"begin,omitempty"`
	End       []byte    `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	Limit     uint32    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListBlobReq) Reset() {
	*x = ListBlobReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBlobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlobReq) ProtoMessage() {}

func (x *ListBlobReq) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlobReq.ProtoReflect.Descriptor instead.
func (*ListBlobReq) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{15}
}

func (x *ListBlobReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ListBlobReq) GetStoreType() StoreType {
	if x != nil {
		return x.StoreType
	}
	return StoreType_UNKNOWN
}

func (x *ListBlobReq) GetBegin() []byte {
	if x != nil {
		return x.Begin
	}
	return nil
}

func (x *ListBlobReq) GetEnd() []byte {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *ListBlobReq) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListBlobRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids [][]byte `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *ListBlobRes) Reset() {
	*x = ListBlobRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBlobRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlobRes) ProtoMessage() {}

func (x *ListBlobRes) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlobRes.ProtoReflect.Descriptor instead.
func (*ListBlobRes) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{16}
}

func (x *ListBlobRes) GetIds() [][]byte {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteBlobReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	StoreType StoreType `protobuf:"varint,2,opt,name=store_type,json=storeType,proto3,enum=StoreType" json:"store_type,omitempty"`
	Id        []byte    `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteBlobReq) Reset() {
	*x = DeleteBlobReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBlobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlobReq) ProtoMessage() {}

func (x *DeleteBlobReq) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlobReq.ProtoReflect.Descriptor instead.
func (*DeleteBlobReq) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteBlobReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteBlobReq) GetStoreType() StoreType {
	if x != nil {
		return x.StoreType
	}
	return StoreType_UNKNOWN
}

func (x *DeleteBlobReq) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type DeleteBlobRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Affected bool `protobuf:"varint,1,opt,name=affected,proto3" json:"affected,omitempty"`
}

func (x *DeleteBlobRes) Reset() {
	*x = DeleteBlobRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBlobRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlobRes) ProtoMessage() {}

func (x *DeleteBlobRes) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlobRes.ProtoReflect.Descriptor instead.
func (*DeleteBlobRes) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteBlobRes) GetAffected() bool {
	if x != nil {
		return x.Affected
	}
	return false
}

type ReadCellReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ReadCellReq) Reset() {
	*x = ReadCellReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadCellReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCellReq) ProtoMessage() {}

func (x *ReadCellReq) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCellReq.ProtoReflect.Descriptor instead.
func (*ReadCellReq) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{19}
}

func (x *ReadCellReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ReadCellRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ReadCellRes) Reset() {
	*x = ReadCellRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadCellRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCellRes) ProtoMessage() {}

func (x *ReadCellRes) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCellRes.ProtoReflect.Descriptor instead.
func (*ReadCellRes) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{20}
}

func (x *ReadCellRes) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CASCellReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	PrevHash []byte `protobuf:"bytes,2,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	Next     []byte `protobuf:"bytes,3,opt,name=next,proto3" json:"next,omitempty"`
}

func (x *CASCellReq) Reset() {
	*x = CASCellReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CASCellReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASCellReq) ProtoMessage() {}

func (x *CASCellReq) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASCellReq.ProtoReflect.Descriptor instead.
func (*CASCellReq) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{21}
}

func (x *CASCellReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CASCellReq) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

func (x *CASCellReq) GetNext() []byte {
	if x != nil {
		return x.Next
	}
	return nil
}

type CASCellRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Current []byte `protobuf:"bytes,1,opt,name=current,proto3" json:"current,omitempty"`
	Swapped bool   `protobuf:"varint,2,opt,name=swapped,proto3" json:"swapped,omitempty"`
}

func (x *CASCellRes) Reset() {
	*x = CASCellRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_got_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CASCellRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASCellRes) ProtoMessage() {}

func (x *CASCellRes) ProtoReflect() protoreflect.Message {
	mi := &file_got_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASCellRes.ProtoReflect.Descriptor instead.
func (*CASCellRes) Descriptor() ([]byte, []int) {
	return file_got_proto_rawDescGZIP(), []int{22}
}

func (x *CASCellRes) GetCurrent() []byte {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *CASCellRes) GetSwapped() bool {
	if x != nil {
		return x.Swapped
	}
	return false
}

var File_got_proto protoreflect.FileDescriptor

var file_got_proto_rawDesc = []byte{
	0x0a, 0x09, 0x67, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x0a, 0x41,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x6e, 0x0a, 0x0a, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73,
	0x61, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x2d, 0x0a, 0x0b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x37, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x72, 0x61, 0x6e, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x22, 0x20, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x7e, 0x0a, 0x0c,
	0x53, 0x65, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x61,
	0x6c, 0x74, 0x12, 0x19, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x05, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x2d, 0x0a,
	0x0b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x37, 0x0a, 0x0d,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a,
	0x05, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x65,
	0x67, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0x23, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x72, 0x61,
	0x6e, 0x63, 0x68, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x23, 0x0a, 0x0f, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22,
	0x11, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x22, 0x5e, 0x0a, 0x0b, 0x50, 0x6f, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x1d, 0x0a, 0x0b, 0x50, 0x6f, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x59, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x29, 0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x22, 0x20, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x59,
	0x0a, 0x0a, 0x41, 0x64, 0x64, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x29,
	0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x22, 0x0c, 0x0a, 0x0a, 0x41, 0x64, 0x64,
	0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x22, 0x88, 0x01, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74,
	0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x0a, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x22, 0x1f, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x03,
	0x69, 0x64, 0x73, 0x22, 0x5c, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f,
	0x62, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x2b, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52,
	0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x22, 0x1f,
	0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x43, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22,
	0x21, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x43, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x4f, 0x0a, 0x0a, 0x43, 0x41, 0x53, 0x43, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x76, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x72, 0x65, 0x76, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6e,
	0x65, 0x78, 0x74, 0x22, 0x40, 0x0a, 0x0a, 0x43, 0x41, 0x53, 0x43, 0x65, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x77, 0x61, 0x70, 0x70, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x77,
	0x61, 0x70, 0x70, 0x65, 0x64, 0x2a, 0x31, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x07, 0x0a, 0x03, 0x52, 0x41, 0x57, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x46, 0x53, 0x10, 0x02,
	0x12, 0x06, 0x0a, 0x02, 0x56, 0x43, 0x10, 0x03, 0x2a, 0x2a, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65,
	0x12, 0x0a, 0x0a, 0x06, 0x46, 0x52, 0x4f, 0x5a, 0x45, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x45, 0x58, 0x50, 0x41, 0x4e, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x48, 0x52, 0x49,
	0x4e, 0x4b, 0x10, 0x02, 0x32, 0x9a, 0x04, 0x0a, 0x08, 0x47, 0x6f, 0x74, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x12, 0x2f, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x72, 0x61, 0x6e, 0x63,
	0x68, 0x12, 0x10, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x00, 0x12, 0x29, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12,
	0x0d, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x0b,
	0x2e, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x34, 0x0a,
	0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x10, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x71, 0x1a,
	0x10, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x63,
	0x68, 0x12, 0x0e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x1a, 0x0e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x12, 0x0d, 0x2e, 0x53, 0x65, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x71, 0x1a,
	0x0b, 0x2e, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x28,
	0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x0c, 0x2e, 0x50, 0x6f, 0x73,
	0x74, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x42,
	0x6c, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x25, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42,
	0x6c, 0x6f, 0x62, 0x12, 0x0b, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x71,
	0x1a, 0x0b, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x2e, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x0e, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x25, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x0b, 0x2e, 0x41, 0x64, 0x64,
	0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x41, 0x64, 0x64, 0x42, 0x6c, 0x6f,
	0x62, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x28, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c,
	0x6f, 0x62, 0x12, 0x0c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x71,
	0x1a, 0x0c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x28, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x43, 0x65, 0x6c, 0x6c, 0x12, 0x0c, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x43, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x52, 0x65, 0x61,
	0x64, 0x43, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x25, 0x0a, 0x07, 0x43, 0x41,
	0x53, 0x43, 0x65, 0x6c, 0x6c, 0x12, 0x0b, 0x2e, 0x43, 0x41, 0x53, 0x43, 0x65, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x43, 0x41, 0x53, 0x43, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x22,
	0x00, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x67, 0x6f, 0x74, 0x76, 0x63, 0x2f, 0x67, 0x6f, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x6f,
	0x74, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_got_proto_rawDescOnce sync.Once
	file_got_proto_rawDescData = file_got_proto_rawDesc
)

func file_got_proto_rawDescGZIP() []byte {
	file_got_proto_rawDescOnce.Do(func() {
		file_got_proto_rawDescData = protoimpl.X.CompressGZIP(file_got_proto_rawDescData)
	})
	return file_got_proto_rawDescData
}

var file_got_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_got_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_got_proto_goTypes = []interface{}{
	(StoreType)(0),          // 0: StoreType
	(Mode)(0),               // 1: Mode
	(*Annotation)(nil),      // 2: Annotation
	(*BranchInfo)(nil),      // 3: BranchInfo
	(*CreateBranchReq)(nil), // 4: CreateBranchReq
	(*GetBranchReq)(nil),    // 5: GetBranchReq
	(*SetBranchReq)(nil),    // 6: SetBranchReq
	(*ListBranchReq)(nil),   // 7: ListBranchReq
	(*ListBranchRes)(nil),   // 8: ListBranchRes
	(*DeleteBranchReq)(nil), // 9: DeleteBranchReq
	(*DeleteBranchRes)(nil), // 10: DeleteBranchRes
	(*PostBlobReq)(nil),     // 11: PostBlobReq
	(*PostBlobRes)(nil),     // 12: PostBlobRes
	(*GetBlobReq)(nil),      // 13: GetBlobReq
	(*GetBlobRes)(nil),      // 14: GetBlobRes
	(*AddBlobReq)(nil),      // 15: AddBlobReq
	(*AddBlobRes)(nil),      // 16: AddBlobRes
	(*ListBlobReq)(nil),     // 17: ListBlobReq
	(*ListBlobRes)(nil),     // 18: ListBlobRes
	(*DeleteBlobReq)(nil),   // 19: DeleteBlobReq
	(*DeleteBlobRes)(nil),   // 20: DeleteBlobRes
	(*ReadCellReq)(nil),     // 21: ReadCellReq
	(*ReadCellRes)(nil),     // 22: ReadCellRes
	(*CASCellReq)(nil),      // 23: CASCellReq
	(*CASCellRes)(nil),      // 24: CASCellRes
}
var file_got_proto_depIdxs = []int32{
	2,  // 0: BranchInfo.annotations:type_name -> Annotation
	1,  // 1: SetBranchReq.mode:type_name -> Mode
	2,  // 2: SetBranchReq.annotations:type_name -> Annotation
	0,  // 3: PostBlobReq.store_type:type_name -> StoreType
	0,  // 4: GetBlobReq.store_type:type_name -> StoreType
	0,  // 5: AddBlobReq.store_type:type_name -> StoreType
	0,  // 6: ListBlobReq.store_type:type_name -> StoreType
	0,  // 7: DeleteBlobReq.store_type:type_name -> StoreType
	4,  // 8: GotSpace.CreateBranch:input_type -> CreateBranchReq
	5,  // 9: GotSpace.GetBranch:input_type -> GetBranchReq
	9,  // 10: GotSpace.DeleteBranch:input_type -> DeleteBranchReq
	7,  // 11: GotSpace.ListBranch:input_type -> ListBranchReq
	6,  // 12: GotSpace.SetBranch:input_type -> SetBranchReq
	11, // 13: GotSpace.PostBlob:input_type -> PostBlobReq
	13, // 14: GotSpace.GetBlob:input_type -> GetBlobReq
	19, // 15: GotSpace.DeleteBlob:input_type -> DeleteBlobReq
	15, // 16: GotSpace.AddBlob:input_type -> AddBlobReq
	17, // 17: GotSpace.ListBlob:input_type -> ListBlobReq
	21, // 18: GotSpace.ReadCell:input_type -> ReadCellReq
	23, // 19: GotSpace.CASCell:input_type -> CASCellReq
	3,  // 20: GotSpace.CreateBranch:output_type -> BranchInfo
	3,  // 21: GotSpace.GetBranch:output_type -> BranchInfo
	10, // 22: GotSpace.DeleteBranch:output_type -> DeleteBranchRes
	8,  // 23: GotSpace.ListBranch:output_type -> ListBranchRes
	3,  // 24: GotSpace.SetBranch:output_type -> BranchInfo
	12, // 25: GotSpace.PostBlob:output_type -> PostBlobRes
	14, // 26: GotSpace.GetBlob:output_type -> GetBlobRes
	20, // 27: GotSpace.DeleteBlob:output_type -> DeleteBlobRes
	16, // 28: GotSpace.AddBlob:output_type -> AddBlobRes
	18, // 29: GotSpace.ListBlob:output_type -> ListBlobRes
	22, // 30: GotSpace.ReadCell:output_type -> ReadCellRes
	24, // 31: GotSpace.CASCell:output_type -> CASCellRes
	20, // [20:32] is the sub-list for method output_type
	8,  // [8:20] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_got_proto_init() }
func file_got_proto_init() {
	if File_got_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_got_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Annotation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BranchInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBranchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBranchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetBranchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBranchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBranchRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBranchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBranchRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostBlobReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostBlobRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlobReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlobRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBlobReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBlobRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBlobReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBlobRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBlobReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBlobRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadCellReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadCellRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CASCellReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_got_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CASCellRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_got_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_got_proto_goTypes,
		DependencyIndexes: file_got_proto_depIdxs,
		EnumInfos:         file_got_proto_enumTypes,
		MessageInfos:      file_got_proto_msgTypes,
	}.Build()
	File_got_proto = out.File
	file_got_proto_rawDesc = nil
	file_got_proto_goTypes = nil
	file_got_proto_depIdxs = nil
}
