// Code generated by capnpc-go. DO NOT EDIT.

package gotfscnp

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type Info capnp.Struct

// Info_TypeID is the unique identifier for the type Info.
const Info_TypeID = 0xe8c4345c559d6872

func NewInfo(s *capnp.Segment) (Info, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Info(st), err
}

func NewRootInfo(s *capnp.Segment) (Info, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Info(st), err
}

func ReadRootInfo(msg *capnp.Message) (Info, error) {
	root, err := msg.Root()
	return Info(root.Struct()), err
}

func (s Info) String() string {
	str, _ := text.Marshal(0xe8c4345c559d6872, capnp.Struct(s))
	return str
}

func (s Info) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Info) DecodeFromPtr(p capnp.Ptr) Info {
	return Info(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Info) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Info) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Info) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Info) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Info) Mode() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s Info) SetMode(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s Info) Attrs() (Attr_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Attr_List(p.List()), err
}

func (s Info) HasAttrs() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Info) SetAttrs(v Attr_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewAttrs sets the attrs field to a newly
// allocated Attr_List, preferring placement in s's segment.
func (s Info) NewAttrs(n int32) (Attr_List, error) {
	l, err := NewAttr_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Attr_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// Info_List is a list of Info.
type Info_List = capnp.StructList[Info]

// NewInfo creates a new list of Info.
func NewInfo_List(s *capnp.Segment, sz int32) (Info_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Info](l), err
}

// Info_Future is a wrapper for a Info promised by a client call.
type Info_Future struct{ *capnp.Future }

func (f Info_Future) Struct() (Info, error) {
	p, err := f.Future.Ptr()
	return Info(p.Struct()), err
}

type Attr capnp.Struct

// Attr_TypeID is the unique identifier for the type Attr.
const Attr_TypeID = 0x84c0f2afeea48fc8

func NewAttr(s *capnp.Segment) (Attr, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Attr(st), err
}

func NewRootAttr(s *capnp.Segment) (Attr, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Attr(st), err
}

func ReadRootAttr(msg *capnp.Message) (Attr, error) {
	root, err := msg.Root()
	return Attr(root.Struct()), err
}

func (s Attr) String() string {
	str, _ := text.Marshal(0x84c0f2afeea48fc8, capnp.Struct(s))
	return str
}

func (s Attr) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Attr) DecodeFromPtr(p capnp.Ptr) Attr {
	return Attr(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Attr) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Attr) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Attr) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Attr) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Attr) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Attr) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Attr) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Attr) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Attr) Value() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s Attr) HasValue() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Attr) SetValue(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

// Attr_List is a list of Attr.
type Attr_List = capnp.StructList[Attr]

// NewAttr creates a new list of Attr.
func NewAttr_List(s *capnp.Segment, sz int32) (Attr_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Attr](l), err
}

// Attr_Future is a wrapper for a Attr promised by a client call.
type Attr_Future struct{ *capnp.Future }

func (f Attr_Future) Struct() (Attr, error) {
	p, err := f.Future.Ptr()
	return Attr(p.Struct()), err
}

const schema_c68fdce9f9749f41 = "x\xda\x12\x98\xe4\xc0b\xc8+\xce\xc4\xc0\x14(\xc1\xca" +
	"\xf6\xffD\xff\x92w\xeb?\x1dha\x10\xe4a\xfc\xef" +
	"8\xbf\xe4\xe7\xcb;\xfd\xc7\x18X\x99\xd8\x19\x18\x04?" +
	"v\x09\xfe\x04\xd1_\xcb\x19\x18\xff\x17e\xcc\x0d\x8d1" +
	"9\xf2\x82!\x90\x87\x11Y%#;\x03\x83p c" +
	"\x97p$\x98\x15\xcaX\xce\xa0\xfb?=\xbf$\xadX" +
	"/9\x91\xb1 \xaf\xc0\xca\xb1\xa4\xa4\x88\x81!\x80\x91" +
	"1\x90\x83\x99\x85\x81\x81\x85\x91\x81APS\x89\x81!" +
	"P\x85\x991\xd0\x80\x89Q\x90\x91Q\x84\x11$\xa8k" +
	"\xc4\xc0\x10\xa8\xc1\xcc\x18h\xc2\xc4\xc8\x9e\x9dZ\xc9\xc8" +
	"\xc3\xc0\xc4\xc8\xc3\xc0(_\x96\x98S\x9a\xca\xc8\xcb\xc0" +
	"\xc4\xc8\xcb\xc0\x88j\xb8g^Z>\x86\xe1Z\x08\xc3" +
	"1\xccvab\xe4\xcf\xcdOIe\xe4``b\xe4" +
	"``\x94O,))*f\xe4c`\x0c`fd" +
	"\x14@\x04\x08\x03#H\x10\x10\x00\x00\xff\xff\xf8\x00F" +
	"l"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_c68fdce9f9749f41,
		Nodes: []uint64{
			0x84c0f2afeea48fc8,
			0xe8c4345c559d6872,
		},
		Compressed: true,
	})
}
